package com.example.Test;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.License;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.EnableAspectJAutoProxy;

@Configuration
@EnableAspectJAutoProxy
public class OpenApiConfig {
    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new io.swagger.v3.oas.models.info.Info().title("Norwegian Assignment")
                .description("AutoGenerated API Documentation for the Norwegian Assignment")
                .termsOfService("")
                .license(new License().name("Dummy License")
                        .url("https://Norwegian.com")).version("Version 1.0")
                .contact(new Contact().name("Norwegian").url("https://Norwegian.com").email("info@Norwegian.com")));
    }

}
